# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Shoker2/Desktop/TS2_Audio_Translator/ui templates/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_SettingsWindow(QMainWindow):
	resized = QtCore.pyqtSignal()

	langs = {
	'Afrikaans': 'af',
	'Albanian': 'sq',
	'Amharic': 'am',
	'Arabic': 'ar',
	'Armenian': 'hy',
	'Assamese': 'as',
	'Aymara': 'ay',
	'Azerbaijani': 'az',
	'Bambara': 'bm',
	'Basque': 'eu',
	'Belarusian': 'be',
	'Bengali': 'bn',
	'Bhojpuri': 'bho',
	'Bosnian': 'bs',
	'Bulgarian': 'bg',
	'Catalan': 'ca',
	'Cebuano': 'ceb',
	'Chichewa': 'ny',
	'Chinese (simplified)': 'zh-CN',
	'Chinese (traditional)': 'zh-TW',
	'Corsican': 'co',
	'Croatian': 'hr',
	'Czech': 'cs',
	'Danish': 'da',
	'Dhivehi': 'dv',
	'Dogri': 'doi',
	'Dutch': 'nl',
	'English': 'en',
	'Esperanto': 'eo',
	'Estonian': 'et',
	'Ewe': 'ee',
	'Filipino': 'tl',
	'Finnish': 'fi',
	'French': 'fr',
	'Frisian': 'fy',
	'Galician': 'gl',
	'Georgian': 'ka',
	'German': 'de',
	'Greek': 'el',
	'Guarani': 'gn',
	'Gujarati': 'gu',
	'Haitian creole': 'ht',
	'Hausa': 'ha',
	'Hawaiian': 'haw',
	'Hebrew': 'iw',
	'Hindi': 'hi',
	'Hmong': 'hmn',
	'Hungarian': 'hu',
	'Icelandic': 'is',
	'Igbo': 'ig',
	'Ilocano': 'ilo',
	'Indonesian': 'id',
	'Irish': 'ga',
	'Italian': 'it',
	'Japanese': 'ja',
	'Javanese': 'jw',
	'Kannada': 'kn',
	'Kazakh': 'kk',
	'Khmer': 'km',
	'Kinyarwanda': 'rw',
	'Konkani': 'gom',
	'Korean': 'ko',
	'Krio': 'kri',
	'Kurdish (kurmanji)': 'ku',
	'Kurdish (sorani)': 'ckb',
	'Kyrgyz': 'ky',
	'Lao': 'lo',
	'Latin': 'la',
	'Latvian': 'lv',
	'Lingala': 'ln',
	'Lithuanian': 'lt',
	'Luganda': 'lg',
	'Luxembourgish': 'lb',
	'Macedonian': 'mk',
	'Maithili': 'mai',
	'Malagasy': 'mg',
	'Malay': 'ms',
	'Malayalam': 'ml',
	'Maltese': 'mt',
	'Maori': 'mi',
	'Marathi': 'mr',
	'Meiteilon (manipuri)': 'mni-Mtei',
	'Mizo': 'lus',
	'Mongolian': 'mn',
	'Myanmar': 'my',
	'Nepali': 'ne',
	'Norwegian': 'no',
	'Odia (oriya)': 'or',
	'Oromo': 'om',
	'Pashto': 'ps',
	'Persian': 'fa',
	'Polish': 'pl',
	'Portuguese': 'pt',
	'Punjabi': 'pa',
	'Quechua': 'qu',
	'Romanian': 'ro',
	'Russian': 'ru',
	'Samoan': 'sm',
	'Sanskrit': 'sa',
	'Scots gaelic': 'gd',
	'Sepedi': 'nso',
	'Serbian': 'sr',
	'Sesotho': 'st',
	'Shona': 'sn',
	'Sindhi': 'sd',
	'Sinhala': 'si',
	'Slovak': 'sk',
	'Slovenian': 'sl',
	'Somali': 'so',
	'Spanish': 'es',
	'Sundanese': 'su',
	'Swahili': 'sw',
	'Swedish': 'sv',
	'Tajik': 'tg',
	'Tamil': 'ta',
	'Tatar': 'tt',
	'Telugu': 'te',
	'Thai': 'th',
	'Tigrinya': 'ti',
	'Tsonga': 'ts',
	'Turkish': 'tr',
	'Turkmen': 'tk',
	'Twi': 'ak',
	'Ukrainian': 'uk',
	'Urdu': 'ur',
	'Uyghur': 'ug',
	'Uzbek': 'uz',
	'Vietnamese': 'vi',
	'Welsh': 'cy',
	'Xhosa': 'xh',
	'Yiddish': 'yi',
	'Yoruba': 'yo',
	'Zulu': 'zu'
	}

	def __init__(self, icon_path=''):
		super(Ui_SettingsWindow, self).__init__()

		if icon_path != '':
			self.setWindowIcon(QtGui.QIcon(icon_path))

		self.setObjectName("SettingsWindow")
		self.resize(500, 450)
		self.centralwidget = QtWidgets.QWidget(self)
		self.centralwidget.setObjectName("centralwidget")
		self.ScrollArea = QtWidgets.QScrollArea(self.centralwidget)
		self.ScrollArea.setGeometry(QtCore.QRect(0, 10, 471, 471))
		self.ScrollArea.setWidgetResizable(True)
		self.ScrollArea.setObjectName("ScrollArea")
		self.scrollAreaWidgetContents = QtWidgets.QWidget()
		self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 469, 469))
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.deviceLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.deviceLabel.sizePolicy().hasHeightForWidth())
		self.deviceLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.deviceLabel.setFont(font)
		self.deviceLabel.setObjectName("deviceLabel")
		self.horizontalLayout_2.addWidget(self.deviceLabel)
		self.deviceComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.deviceComboBox.setFont(font)
		self.deviceComboBox.setObjectName("deviceComboBox")
		self.horizontalLayout_2.addWidget(self.deviceComboBox)
		self.verticalLayout.addLayout(self.horizontalLayout_2)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.modelLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
		self.modelLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.modelLabel.setFont(font)
		self.modelLabel.setObjectName("modelLabel")
		self.horizontalLayout.addWidget(self.modelLabel)
		self.modelComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.modelComboBox.setFont(font)
		self.modelComboBox.setObjectName("modelComboBox")
		self.horizontalLayout.addWidget(self.modelComboBox)
		self.verticalLayout.addLayout(self.horizontalLayout)
		self.activeCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.activeCheckBox.setFont(font)
		self.activeCheckBox.setObjectName("activeCheckBox")
		self.verticalLayout.addWidget(self.activeCheckBox)
		self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
		self.line.setFrameShape(QtWidgets.QFrame.HLine)
		self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line.setObjectName("line")
		self.verticalLayout.addWidget(self.line)
		self.translateCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.translateCheckBox.setFont(font)
		self.translateCheckBox.setObjectName("translateCheckBox")
		self.verticalLayout.addWidget(self.translateCheckBox)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.translateFromLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.translateFromLabel.sizePolicy().hasHeightForWidth())
		self.translateFromLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.translateFromLabel.setFont(font)
		self.translateFromLabel.setObjectName("translateFromLabel")
		self.horizontalLayout_3.addWidget(self.translateFromLabel)
		self.translateFromComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.translateFromComboBox.setFont(font)
		self.translateFromComboBox.setObjectName("translateFromComboBox")
		self.horizontalLayout_3.addWidget(self.translateFromComboBox)
		self.verticalLayout.addLayout(self.horizontalLayout_3)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.translateToLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.translateToLabel.sizePolicy().hasHeightForWidth())
		self.translateToLabel.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.translateToLabel.setFont(font)
		self.translateToLabel.setObjectName("translateToLabel")
		self.horizontalLayout_4.addWidget(self.translateToLabel)
		self.translateToComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.translateToComboBox.setFont(font)
		self.translateToComboBox.setObjectName("translateToComboBox")
		self.horizontalLayout_4.addWidget(self.translateToComboBox)
		self.verticalLayout.addLayout(self.horizontalLayout_4)
		self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
		self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.verticalLayout.addWidget(self.line_2)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.customizePshButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.customizePshButton.setFont(font)
		self.customizePshButton.setObjectName("customizePshButton")
		self.horizontalLayout_5.addWidget(self.customizePshButton)
		self.verticalLayout.addLayout(self.horizontalLayout_5)
		self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.fontComboBox = QtWidgets.QFontComboBox(self.scrollAreaWidgetContents)
		self.fontComboBox.setObjectName("fontComboBox")
		self.fontComboBox.setFont(font)
		self.horizontalLayout_6.addWidget(self.fontComboBox)
		self.fontSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
		self.fontSpinBox.setFont(font)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.fontSpinBox.sizePolicy().hasHeightForWidth())
		self.fontSpinBox.setSizePolicy(sizePolicy)
		self.fontSpinBox.setMinimum(1)
		self.fontSpinBox.setObjectName("fontSpinBox")
		self.horizontalLayout_6.addWidget(self.fontSpinBox)
		self.verticalLayout.addLayout(self.horizontalLayout_6)
		self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
		self.setCentralWidget(self.centralwidget)

		QtCore.QMetaObject.connectSlotsByName(self)

		self.resized.connect(self.auto_resize) # Делаю ивент на изменение размера окна

		self.setWindowTitle("Settings")
		self.deviceLabel.setText("Device")
		self.modelLabel.setText("Recognition model")
		self.translateCheckBox.setText("Translate")
		self.translateFromLabel.setText("Translate from")
		self.translateToLabel.setText("Translate to")
		self.activeCheckBox.setText("Activate")
		self.customizePshButton.setText("Customize Output")

		self.fill_data()

		self.deviceComboBox.currentTextChanged.connect(lambda: self.save_data())
		self.modelComboBox.currentTextChanged.connect(lambda: self.save_data())
		self.translateFromComboBox.currentTextChanged.connect(lambda: self.save_data())
		self.translateToComboBox.currentTextChanged.connect(lambda: self.save_data())
		self.fontComboBox.currentTextChanged.connect(lambda: self.save_data())
		self.activeCheckBox.toggled.connect(lambda: self.save_data())
		self.translateCheckBox.toggled.connect(lambda: self.save_data())
		self.fontSpinBox.valueChanged.connect(lambda: self.save_data())

		self.customizePshButton.clicked.connect(lambda: self.customizePshButton_pressed())
	
	def resizeEvent(self, event):
		self.resized.emit()
		return super(Ui_SettingsWindow, self).resizeEvent(event)
	
	def auto_resize(self):
		self.ScrollArea.setGeometry(0,0, self.size().width(), self.size().height())
	
	def fill_data(self):
		pass

	def save_data(self):
		pass

	def customizePshButton_pressed(self):
		pass


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)

	ui = Ui_SettingsWindow()
	ui.show()

	sys.exit(app.exec_())
